version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  netlify-deploy-preview:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn build
            - run: yarn add netlify-cli
            - run: yarn netlify deploy -d build -a ${NETLIFY_TOKEN} -s ${NETLIFY_API_ID}

  netlify-deploy-production:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn build
            - run: yarn add netlify-cli
            - run: yarn netlify deploy -p -d build -a ${NETLIFY_TOKEN} -s ${NETLIFY_API_ID}

  run-mabl-test:
    executor:
      name: node/default
    steps:
      - deploy:
          name: call mabl Deployment API Event
          command: |
            curl -s "https://api.mabl.com/events/deployment" \
              -u "key:${MABL_API_KEY}" \
              -H "Content-Type:application/json" \
              -d "{\"environment_id\":\"bIIfJiJ4lefJcKozgmNBPw-e\",\"application_id\":\"Kew3dKp0yhv4MDOPXGNu7w-a\",\"plan_overrides\":{\"web_url\":\"https://61c72a21fa1ce466f1596b4c--test-automation-sandbox.netlify.app/\"},\"revision\":\"{{ .Revision }}\"}"

workflows:
  netlify-deploy-workflow:
    jobs:
      - netlify-deploy-preview:
          filters:
            branches:
              only:
                - /deploy-preview-.*/
      
      - netlify-deploy-production:
          filters:
            branches:
              only: master
      
      - run-mabl-test:
          requires:
              - netlify-deploy-preview
              - netlify-deploy-
