version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  netlify-deploy-preview:
    executor:
      name: node/default
    environment:
      REVISION_NO: <<pipeline.git.revision>>
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn build
            - run: yarn add netlify-cli
            - run: yarn netlify deploy -d build -a ${NETLIFY_TOKEN} -s ${NETLIFY_API_ID}

  netlify-deploy-production:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn build
            - run: yarn add netlify-cli
            - run: yarn netlify deploy -p -d build -a ${NETLIFY_TOKEN} -s ${NETLIFY_API_ID}

  run-mabl-test:
    executor:
      name: node/default
    environment:
      REVISION: ${CIRCLE_PULL_REQUEST##*/}
    steps:
      - run:
          name: "Setup PR_NUMBER from ${CIRCLE_PULL_REQUEST}"
          command: |
            echo 'export PR_NUMBER=${CIRCLE_PULL_REQUEST##*/}' >> $BASH_ENV
      - run:
          name: Call mabl Deployment API Event
          command: |
            curl -s "https://api.mabl.com/events/deployment" \
              -u "key:${MABL_API_KEY}" \
              -H "Content-Type:application/json" \
              -d "{\"environment_id\":\"bIIfJiJ4lefJcKozgmNBPw-e\",\"application_id\":\"Kew3dKp0yhv4MDOPXGNu7w-a\",\"plan_overrides\":{\"web_url\":\"https://deploy-preview-${PR_NUMBER}--test-automation-sandbox.netlify.app/\"},\"revision\":\"${CIRCLE_SHA1}\"}"
  notify-slack:
    executor:
      name: node/default
    steps:
      - run:
          name: "Setup PR_NUMBER from ${CIRCLE_PULL_REQUEST}"
          command: |
            echo 'export PR_NUMBER=${CIRCLE_PULL_REQUEST##*/}' >> $BASH_ENV
      - run:
          name: Post message to slack
          command: |
            curl -X POST -H 'Content-type: application/json' --data '{"text":"All done. Preview URL: https://deploy-preview-${REVISION}--test-automation-sandbox.netlify.app/, Mabl test is running: https://app.mabl.com/workspaces/-/output/deployments"}' ${SLACK_HOOK_URL}

workflows:
  netlify-deploy-workflow:
    jobs:
      - netlify-deploy-preview:
          filters:
            branches:
              only:
                - /deploy-preview-.*/
      
      - netlify-deploy-production:
          filters:
            branches:
              only: master
      
      - run-mabl-test:
          requires:
              - netlify-deploy-preview
              - netlify-deploy-production
      
      - notify-slack:
          requires:
              - run-mabl-test