version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  netlify-deploy-preview:
    executor:
      name: node/default
    environment:
      REVISION_NO: <<pipeline.git.revision>>
      PREVIEW_URL: "https://deploy-preview-${CIRCLE_PR_NUMBER}--test-automation-sandbox.netlify.app/"
      MABL_RESULT_URL: "https://app.mabl.com/workspaces/-/output/deployments"
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn build
            - run: yarn add netlify-cli
            - run: yarn netlify deploy -d build -a ${NETLIFY_TOKEN} -s ${NETLIFY_API_ID}

  netlify-deploy-production:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn build
            - run: yarn add netlify-cli
            - run: yarn netlify deploy -p -d build -a ${NETLIFY_TOKEN} -s ${NETLIFY_API_ID}

  run-mabl-test:
    executor:
      name: node/default
    steps:
      - deploy:
          name: Call mabl Deployment API Event
          command: |
            curl -s "https://api.mabl.com/events/deployment" \
              -u "key:${MABL_API_KEY}" \
              -H "Content-Type:application/json" \
              -d "{\"environment_id\":\"bIIfJiJ4lefJcKozgmNBPw-e\",\"application_id\":\"Kew3dKp0yhv4MDOPXGNu7w-a\",\"plan_overrides\":{\"web_url\":\"$PREVIEW_URL\"},\"revision\":\"$REVISION_NO\"}"
  notify-slack:
    executor:
      name: node/default
    steps:
      - deploy:
          name: Post message to slack
          command: |
            curl -X POST -H 'Content-type: application/json' --data '{"text":"All done. Preview: $PREVIEW_URL, Mabl: $MABL_RESULT_URL"}' $SLACK_HOOK_URL
workflows:
  netlify-deploy-workflow:
    jobs:
      - netlify-deploy-preview:
          filters:
            branches:
              only:
                - /deploy-preview-.*/
      
      - netlify-deploy-production:
          filters:
            branches:
              only: master
      
      - run-mabl-test:
          requires:
              - netlify-deploy-preview
              - netlify-deploy-production
      
      - notify-slack:
          requires:
              - run-mabl-test