version: 2.1
orbs:
  node: circleci/node@1.1.6

jobs:
  netlify-deploy:
    dexecutor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn build
            - run: yarn add netlify-cli
            - run: yarn netlify deploy -p -d build -a ${NETLIFY_TOKEN} -s ${NETLIFY_SITE_ID}

workflows:
  call-netlify-deploy:
    jobs:
      - build-and-test